return {
	{
		key = "sniper_aim", setting_id = "sniper_aim",
		hook = { kind = "effect_template", template = "renegade_sniper_laser" },
		audio = { kind = "file", path = "mods/Signal Repeater/audio/cues/sniper_aim.ogg" },
		range = 60,
		lpf = { { 0, 0 }, { 10, 20 } },
		mode = "loop",
		max_duration = 6,
		suppress_events = { "wwise/events/weapon/play_combat_weapon_las_sniper_target_beam" },
	},
	{
		key = "plasma_charge", setting_id = "plasma_charge",
		hook = { kind = "effect_template", template = "renegade_plasma_gunner_charge_up" },
		layers = {
			{ kind = "glob", pattern = "mods/Signal Repeater/audio/cues/plasma_charge/tone/*.ogg" },
			{ kind = "glob", pattern = "mods/Signal Repeater/audio/cues/plasma_charge/overlay/*.ogg" },
		},
		range = 80,
		lpf = { { 0, 0 }, { 49.5, 0 }, { 86.4, 26 }, { 150, 50 } },
		mode = "loop",
		max_duration = 5,
		suppress_events = { "wwise/events/weapon/play_minion_plasmapistol_charge_02" },
	},
	{
		key = "mutant_charge", setting_id = "mutant_charge",
		hook = {
			kind = "sound_event",
			event = "wwise/events/minions/play_enemy_mutant_charger_charge_growl",
			stop_event = "wwise/events/minions/stop_enemy_mutant_charger_charge_growl",
		},
		audio = { kind = "glob", pattern = "mods/Signal Repeater/audio/cues/mutant_charge/*.ogg" },
		range = 70,
		lpf = { { 0, 0 }, { 8.6, 10 }, { 70, 30 } },
		mode = "loop",
		max_duration = 5,
	},
	{
		key = "hound_approach", setting_id = "hound_approach",
		hook = {
			kind = "sound_event",
			event = "wwise/events/minions/play_enemy_chaos_hound_vce_bark",
			breeds = { "chaos_hound", "chaos_armored_hound" },
		},
		audio = { kind = "glob", pattern = "mods/Signal Repeater/audio/cues/hound_approach/*.ogg" },
		range = 80,
		lpf = { { 0, 0 }, { 200, 50 } },
		mode = "play_once",
		overlap = true,
		max_duration = 4,
	},
	{
		key = "hound_leap", setting_id = "hound_leap",
		hook = {
			kind = "sound_event",
			event = "wwise/events/minions/play_enemy_chaos_hound_vce_leap",
			breeds = { "chaos_hound", "chaos_armored_hound" },
		},
		audio = { kind = "glob", pattern = "mods/Signal Repeater/audio/cues/hound_leap/*.ogg" },
		range = 80,
		lpf = { { 0, 0 }, { 80, 43 } },
		mode = "play_once",
		overlap = true,
		gain = 1.3,
		max_duration = 3,
	},
	{
		key = "hound_growl", setting_id = "hound_growl",
		hook = {
			kind = "sound_event",
			event = "wwise/events/minions/play_enemy_chaos_hound_vce_growl",
			breeds = { "chaos_hound", "chaos_armored_hound" },
		},
		audio = { kind = "glob", pattern = "mods/Signal Repeater/audio/cues/hound_growl/*.ogg" },
		range = 80,
		lpf = { { 0, 0 }, { 80, 43 } },
		mode = "play_once",
		overlap = true,
		max_duration = 3,
	},
	{
		key = "hound_footsteps", setting_id = "hound_footsteps",
		hook = {
			kind = "sound_event",
			event = "wwise/events/minions/play_enemy_chaos_hound_footstep",
			breeds = { "chaos_hound", "chaos_armored_hound" },
		},
		audio = {
			kind = "surface",
			base = "mods/Signal Repeater/audio/cues/hound_footsteps",
			surfaces = "chaos_hound",
			gaits = { { "walk", 0 } },
		},
		range = 80,
		lpf = { { 0, 0 }, { 80, 60 } },
		mode = "play_once",
		overlap = true,
		gain = 1.0,
		min_interval = 0.05,
		max_duration = 1,
	},
	{
		key = "mutant_footsteps", setting_id = "mutant_footsteps",
		hook = {
			kind = "sound_event",
			event = "wwise/events/minions/play_mutant_charger_footstep_boots_heavy",
			breeds = { "cultist_mutant", "cultist_mutant_mutator" },
		},
		audio = {
			kind = "surface",
			base = "mods/Signal Repeater/audio/cues/mutant_footsteps",
			surfaces = "mutant",
			gaits = { { "walk", 0 } },
		},
		range = 80,
		lpf = { { 0, 0 }, { 80, 60 } },
		mode = "play_once",
		overlap = true,
		gain = 0.94,
		min_interval = 0.05,
		max_duration = 1,
	},
	{
		key = "mutant_breath", setting_id = "mutant_breath",
		hook = {
			kind = "sound_event",
			event = "wwise/events/minions/play_enemy_mutant_charger_run_breath",
			breeds = { "cultist_mutant", "cultist_mutant_mutator" },
		},
		audio = { kind = "glob", pattern = "mods/Signal Repeater/audio/cues/mutant_breath/*.ogg" },
		range = 70,
		lpf = { { 0, 0 }, { 8.6, 10 }, { 70, 30 } },
		mode = "play_once",
		overlap = true,
		max_duration = 3,
	},
	{
		key = "mutant_rattle", setting_id = "mutant_rattle",
		hook = {
			kind = "sound_event",
			event = "wwise/events/minions/play_enemy_mutant_charger_run_rattle",
			breeds = { "cultist_mutant", "cultist_mutant_mutator" },
		},
		audio = { kind = "glob", pattern = "mods/Signal Repeater/audio/cues/mutant_rattle/*.ogg" },
		range = 50,
		lpf = { { 0, 0 }, { 50, 45 } },
		mode = "play_once",
		overlap = true,
		max_duration = 3,
	},
	{
		key = "flamer_tank", setting_id = "flamer_tank",
		hook = {
			kind = "sound_event",
			event = "wwise/events/minions/play_enemy_cultist_flamer_foley_tank",
			breeds = { "cultist_flamer", "renegade_flamer", "renegade_flamer_mutator" },
		},
		audio = { kind = "glob", pattern = "mods/Signal Repeater/audio/cues/flamer_tank/*.ogg" },
		range = 70,
		lpf = { { 0, 0 }, { 70, 45 } },
		mode = "play_once",
		overlap = true,
		gain = 1.4,
		alerted_gain = 0.5,
		min_interval = 0.05,
		max_duration = 2,
	},
	{
		key = "flamer_aim", setting_id = "flamer_aim",
		hook = {
			kind = "utility",
			path = "scripts/utilities/flamer",
			start = { func = "start_aiming_fx", unit_arg = 2 },
			breeds = { "cultist_flamer", "renegade_flamer", "renegade_flamer_mutator" },
		},
		audio = { kind = "glob", pattern = "mods/Signal Repeater/audio/cues/flamer_aim/*.ogg" },
		range = 120,
		lpf = { { 0, 0 }, { 120, 65 } },
		mode = "play_once",
		overlap = true,
		gain = 1.3,
		max_duration = 3,
	},
	{
		key = "flamer_flame_dreg", setting_id = "flamer_flame_dreg",
		hook = {
			kind = "utility",
			path = "scripts/utilities/flamer",
			start = { func = "start_shooting_fx", unit_arg = 2 },
			stop = { func = "stop_fx", unit_arg = 1 },
			breeds = { "cultist_flamer" },
		},
		audio = { kind = "glob", pattern = "mods/Signal Repeater/audio/cues/flamer_flame_dreg/*.ogg" },
		range = 120,
		lpf = { { 0, 0 }, { 120, 65 } },
		mode = "loop",
		max_duration = 10,
	},
	{
		key = "flamer_flame_scab", setting_id = "flamer_flame_scab",
		hook = {
			kind = "utility",
			path = "scripts/utilities/flamer",
			start = { func = "start_shooting_fx", unit_arg = 2 },
			stop = { func = "stop_fx", unit_arg = 1 },
			breeds = { "renegade_flamer", "renegade_flamer_mutator" },
		},
		audio = { kind = "glob", pattern = "mods/Signal Repeater/audio/cues/flamer_flame_scab/*.ogg" },
		range = 80,
		lpf = { { 0, 0 }, { 80, 60 } },
		mode = "loop",
		max_duration = 10,
	},
	{
		key = "flamer_ignite", setting_id = "flamer_ignite",
		hook = { kind = "sound_event", event = "wwise/events/minions/play_cultist_flamer_proximity_warning" },
		audio = { kind = "glob", pattern = "mods/Signal Repeater/audio/cues/flamer_ignite/*.ogg" },
		range = 70,
		lpf = { { 0, 0 }, { 70, 45 } },
		mode = "play_once",
		overlap = true,
		max_duration = 3.5,
	},
	{
		key = "reaper_vo_alerted", setting_id = "reaper_vo_alerted",
		hook = { kind = "vo_event", loc_prefix = "loc_enemy_chaos_ogryn_heavy_gunner_a__alerted_idle" },
		audio = { kind = "vo", dir = "mods/Signal Repeater/audio/vo/reaper_alerted" },
		range = 70,
		lpf = { { 0, 0 }, { 70, 32 } },
		mode = "play_once",
		overlap = true,
		max_duration = 5,
	},
	{
		key = "reaper_vo_shooting", setting_id = "reaper_vo_shooting",
		hook = { kind = "vo_event", loc_prefix = "loc_enemy_chaos_ogryn_heavy_gunner_a__shooting" },
		audio = { kind = "vo", dir = "mods/Signal Repeater/audio/vo/reaper_shooting" },
		range = 70,
		lpf = { { 0, 0 }, { 70, 32 } },
		mode = "play_once",
		overlap = true,
		max_duration = 5,
	},
	{
		key = "crusher_vo_alerted", setting_id = "crusher_vo_alerted",
		hook = { kind = "vo_event", loc_prefix = "loc_enemy_chaos_ogryn_armoured_executor_a__alerted_idle" },
		audio = { kind = "vo", dir = "mods/Signal Repeater/audio/vo/crusher_alerted" },
		range = 100,
		lpf = { { 0, 0 }, { 30, 40 }, { 100, 80 } },
		mode = "play_once",
		overlap = true,
		max_duration = 5,
	},
	{
		key = "crusher_vo_assault", setting_id = "crusher_vo_assault",
		hook = { kind = "vo_event", loc_prefix = "loc_enemy_chaos_ogryn_armoured_executor_a__assault" },
		audio = { kind = "vo", dir = "mods/Signal Repeater/audio/vo/crusher_assault" },
		range = 100,
		lpf = { { 0, 0 }, { 30, 40 }, { 100, 80 } },
		mode = "play_once",
		overlap = true,
		max_duration = 5,
	},
	{
		key = "crusher_special", setting_id = "crusher_special",
		hook = { kind = "sound_event", event = "wwise/events/minions/play_enemy_chaos_ogryn_armoured_executor_a__special_attack_vce" },
		audio = { kind = "glob", pattern = "mods/Signal Repeater/audio/cues/crusher_special/*.ogg" },
		range = 100,
		lpf = { { 0, 0 }, { 30, 40 }, { 100, 80 } },
		mode = "play_once",
		overlap = true,
		max_duration = 3,
	},
	{
		key = "crusher_melee", setting_id = "crusher_melee",
		hook = { kind = "sound_event", event = "wwise/events/minions/play_enemy_chaos_ogryn_armoured_executor_a__melee_attack_vce" },
		audio = { kind = "glob", pattern = "mods/Signal Repeater/audio/cues/crusher_melee/*.ogg" },
		range = 100,
		lpf = { { 0, 0 }, { 30, 40 }, { 100, 80 } },
		mode = "play_once",
		overlap = true,
		max_duration = 2,
	},
	{
		key = "crusher_swing", setting_id = "crusher_swing",
		hook = { kind = "sound_event", pattern = "^wwise/events/weapon/play_minion_swing_2h_blunt_large_" },
		audio = { kind = "glob", pattern = "mods/Signal Repeater/audio/cues/crusher_swing/*.ogg" },
		range = 50,
		lpf = { { 0, 0 }, { 50, 30 } },
		mode = "play_once",
		overlap = true,
		max_duration = 2,
	},
	{
		key = "bulwark_ready", setting_id = "bulwark_ready",
		hook = { kind = "sound_event", event = "wwise/events/minions/play_enemy_bulwark_ogryn_foley_drastic_short" },
		audio = { kind = "glob", pattern = "mods/Signal Repeater/audio/cues/bulwark_ready/*.ogg" },
		range = 50,
		lpf = { { 0, 0 }, { 50, 30 } },
		mode = "play_once",
		overlap = true,
		max_duration = 2,
	},
	{
		key = "bulwark_swing", setting_id = "bulwark_swing",
		hook = { kind = "sound_event", event = "wwise/events/minions/play_combat_weapon_bulwark_shield_swing" },
		audio = { kind = "glob", pattern = "mods/Signal Repeater/audio/cues/bulwark_swing/*.ogg" },
		range = 50,
		lpf = { { 0, 0 }, { 50, 30 } },
		mode = "play_once",
		overlap = true,
		max_duration = 2,
	},
	{
		key = "bulwark_melee", setting_id = "bulwark_melee",
		hook = { kind = "sound_event", event = "wwise/events/minions/play_enemy_chaos_ogryn_bulwark_a__melee_attack_vce" },
		audio = { kind = "glob", pattern = "mods/Signal Repeater/audio/cues/bulwark_melee/*.ogg" },
		range = 100,
		lpf = { { 0, 0 }, { 30, 40 }, { 100, 80 } },
		mode = "play_once",
		overlap = true,
		max_duration = 2,
	},
	{
		key = "bulwark_special", setting_id = "bulwark_special",
		hook = { kind = "sound_event", event = "wwise/events/minions/play_enemy_chaos_ogryn_bulwark_a__special_attack_vce" },
		audio = { kind = "glob", pattern = "mods/Signal Repeater/audio/cues/bulwark_special/*.ogg" },
		range = 100,
		lpf = { { 0, 0 }, { 30, 40 }, { 100, 80 } },
		mode = "play_once",
		overlap = true,
		max_duration = 3,
	},
	{
		key = "reaper_ready", setting_id = "reaper_ready",
		hook = { kind = "sound_event", event = "wwise/events/minions/play_chaos_ogryn_heavy_gunner_foley_drastic_short" },
		audio = { kind = "glob", pattern = "mods/Signal Repeater/audio/cues/reaper_ready/*.ogg" },
		range = 60,
		lpf = { { 0, 0 }, { 60, 45 } },
		mode = "play_once",
		overlap = true,
		max_duration = 2,
	},
	{
		key = "reaper_melee", setting_id = "reaper_melee",
		hook = { kind = "sound_event", event = "wwise/events/minions/play_enemy_chaos_ogryn_heavy_gunner__melee_attack_vce" },
		audio = { kind = "glob", pattern = "mods/Signal Repeater/audio/cues/reaper_melee/*.ogg" },
		range = 70,
		lpf = { { 0, 0 }, { 70, 32 } },
		mode = "play_once",
		overlap = true,
		max_duration = 2,
	},
	{
		key = "reaper_fire", setting_id = "reaper_fire",
		hook = { kind = "effect_template", template = "chaos_ogryn_gunner_heavy_stubber" },
		audio = { kind = "glob", pattern = "mods/Signal Repeater/audio/cues/reaper_fire/*.ogg" },
		range = 135,
		lpf = { { 0, 0 }, { 135, 80 } },
		mode = "loop",
		max_duration = 12,
		suppress_events = { "wwise/events/weapon/play_combat_weapon_heavy_stubber_auto_chaos" },
	},
	{
		key = "trapper_windup", setting_id = "trapper_windup",
		hook = {
			kind = "inventory",
			events = { "wwise/events/minions/play_weapon_netgunner_wind_up" },
			breeds = { "renegade_netgunner" },
		},
		audio = { kind = "file", path = "mods/Signal Repeater/audio/cues/trapper_windup.ogg" },
		range = 60,
		lpf = { { 0, 0 }, { 80, 60 } },
		mode = "play_once",
		max_duration = 4,
		suppress_events = { "wwise/events/minions/play_weapon_netgunner_wind_up" },
	},
	{
		key = "trapper_interrupted", setting_id = "trapper_interrupted",
		hook = {
			kind = "inventory",
			events = { "wwise/events/minions/play_weapon_netgunner_interupted" },
			breeds = { "renegade_netgunner" },
		},
		audio = { kind = "glob", pattern = "mods/Signal Repeater/audio/cues/trapper_interrupted/*.ogg" },
		range = 60,
		lpf = { { 0, 0 }, { 80, 60 } },
		mode = "play_once",
		overlap = true,
		max_duration = 2,
		suppress_events = { "wwise/events/minions/play_weapon_netgunner_interupted" },
	},
	{
		key = "trapper_reload", setting_id = "trapper_reload",
		hook = {
			kind = "sound_event",
			event = "wwise/events/minions/play_netgunner_drastic_short",
			breeds = { "renegade_netgunner" },
		},
		audio = { kind = "glob", pattern = "mods/Signal Repeater/audio/cues/trapper_reload/*.ogg" },
		range = 60,
		lpf = { { 0, 0 }, { 60, 45 } },
		mode = "play_once",
		overlap = true,
		max_duration = 1.5,
	},
	{
		key = "trapper_proximity", setting_id = "trapper_proximity",
		hook = { kind = "sound_event", event = "wwise/events/minions/play_netgunner_proximity_warning" },
		audio = { kind = "glob", pattern = "mods/Signal Repeater/audio/cues/trapper_proximity/*.ogg" },
		range = 70,
		lpf = { { 0, 0 }, { 70, 45 } },
		mode = "play_once",
		overlap = true,
		max_duration = 3.5,
	},
	{
		key = "trapper_footsteps", setting_id = "trapper_footsteps",
		hook = {
			kind = "sound_event",
			event = "wwise/events/minions/play_netgunner_footsteps",
			breeds = { "renegade_netgunner" },
		},
		audio = {
			kind = "surface",
			base = "mods/Signal Repeater/audio/cues/trapper_footsteps",
			surfaces = "netgunner",
			gaits = { { "run", 3.75 }, { "walk", 0 } },
		},
		range = 60,
		lpf = { { 0, 0 }, { 60, 45 } },
		mode = "play_once",
		overlap = true,
		gain = 1.0,
		min_interval = 0.05,
		max_duration = 1,
	},
	{
		key = "mauler_swing", setting_id = "mauler_swing",
		hook = { kind = "sound_event", event = "wwise/events/weapon/play_minion_swing_chainaxe" },
		audio = { kind = "glob", pattern = "mods/Signal Repeater/audio/cues/mauler_swing/*.ogg" },
		range = 45,
		lpf = { { 0, 0 }, { 45, 35 } },
		mode = "play_once",
		overlap = true,
		max_duration = 2,
	},
	{
		key = "mauler_melee", setting_id = "mauler_melee",
		hook = { kind = "sound_event", event = "wwise/events/minions/play_enemy_traitor_executor__melee_attack_short_vce" },
		audio = { kind = "glob", pattern = "mods/Signal Repeater/audio/cues/mauler_melee/*.ogg" },
		range = 100,
		lpf = { { 0, 0 }, { 30, 40 }, { 100, 80 } },
		mode = "play_once",
		overlap = true,
		max_duration = 2,
	},
	{
		key = "mauler_special", setting_id = "mauler_special",
		hook = { kind = "sound_event", event = "wwise/events/minions/play_enemy_traitor_executor__special_attack_vce" },
		audio = { kind = "glob", pattern = "mods/Signal Repeater/audio/cues/mauler_special/*.ogg" },
		range = 100,
		lpf = { { 0, 0 }, { 30, 40 }, { 100, 80 } },
		mode = "play_once",
		overlap = true,
		max_duration = 3,
	},
	{
		key = "mauler_footsteps", setting_id = "mauler_footsteps",
		hook = {
			kind = "sound_event",
			event = "wwise/events/minions/play_minion_footsteps_boots_heavy",
			breeds = { "renegade_executor" },
		},
		audio = {
			kind = "surface",
			base = "mods/Signal Repeater/audio/cues/boots_heavy_footsteps",
			surfaces = "boots_heavy",
			gaits = { { "run", 3.6 }, { "walk", 0 } },
		},
		range = 35,
		lpf = { { 0, 0 }, { 35, 45 } },
		mode = "play_once",
		overlap = true,
		gain = 0.94,
		min_interval = 0.05,
		max_duration = 1,
	},
	{
		key = "bomber_throw", setting_id = "bomber_throw",
		hook = { kind = "vo_event", loc_prefix = "loc_enemy_grenadier_a__throwing_grenade" },
		audio = { kind = "vo", dir = "mods/Signal Repeater/audio/vo/bomber_throw" },
		range = 100,
		lpf = { { 0, 0 }, { 100, 45 } },
		mode = "play_once",
		overlap = true,
		max_duration = 5,
	},
	{
		key = "bomber_footsteps", setting_id = "bomber_footsteps",
		hook = {
			kind = "sound_event",
			event = "wwise/events/minions/play_traitor_guard_grenadier_footsteps",
			breeds = { "renegade_grenadier" },
		},
		audio = {
			kind = "surface",
			base = "mods/Signal Repeater/audio/cues/grenadier_footsteps",
			surfaces = "grenadier",
			gaits = { { "run", 3.55 }, { "walk", 0 } },
		},
		range = 60,
		lpf = { { 0, 0 }, { 60, 45 } },
		mode = "play_once",
		overlap = true,
		gain = 1.0,
		min_interval = 0.05,
		max_duration = 1,
	},
	{
		key = "scab_flamer_footsteps", setting_id = "scab_flamer_footsteps",
		hook = {
			kind = "sound_event",
			event = "wwise/events/minions/play_traitor_guard_grenadier_footsteps",
			breeds = { "renegade_flamer" },
		},
		audio = {
			kind = "surface",
			base = "mods/Signal Repeater/audio/cues/grenadier_footsteps",
			surfaces = "grenadier",
			gaits = { { "run", 3.9 }, { "walk", 0 } },
		},
		range = 60,
		lpf = { { 0, 0 }, { 60, 45 } },
		mode = "play_once",
		overlap = true,
		gain = 1.0,
		min_interval = 0.05,
		max_duration = 1,
	},
	{
		key = "dreg_flamer_footsteps", setting_id = "dreg_flamer_footsteps",
		hook = {
			kind = "sound_event",
			event = "wwise/events/minions/play_minion_footsteps_wrapped_feet_specials",
			breeds = { "cultist_flamer" },
		},
		audio = {
			kind = "surface",
			base = "mods/Signal Repeater/audio/cues/wrapped_feet_footsteps",
			surfaces = "wrapped_feet",
			gaits = { { "walk", 0 } },
		},
		range = 60,
		lpf = { { 0, 0 }, { 60, 45 } },
		mode = "play_once",
		overlap = true,
		gain = 1.06,
		min_interval = 0.05,
		max_duration = 1,
	},
	{
		key = "sniper_footsteps", setting_id = "sniper_footsteps",
		hook = {
			kind = "sound_event",
			event = "wwise/events/minions/play_netgunner_footsteps",
			breeds = { "renegade_sniper" },
		},
		audio = {
			kind = "surface",
			base = "mods/Signal Repeater/audio/cues/trapper_footsteps",
			surfaces = "netgunner",
			gaits = { { "run", 3.55 }, { "walk", 0 } },
		},
		range = 60,
		lpf = { { 0, 0 }, { 60, 45 } },
		mode = "play_once",
		overlap = true,
		gain = 1.0,
		min_interval = 0.05,
		max_duration = 1,
	},
	{
		key = "poxburster_footsteps", setting_id = "poxburster_footsteps",
		hook = {
			kind = "sound_event",
			event = "wwise/events/minions/play_minion_poxwalker_bomber_footstep_boots_heavy",
			breeds = { "chaos_poxwalker_bomber" },
		},
		audio = {
			kind = "surface",
			base = "mods/Signal Repeater/audio/cues/poxburster_footsteps",
			surfaces = "poxwalker_bomber",
			gaits = { { "run", 3.5 }, { "walk", 0 } },
		},
		range = 80,
		lpf = { { 0, 0 }, { 80, 60 } },
		mode = "play_once",
		overlap = true,
		gain = 1.0,
		min_interval = 0.05,
		max_duration = 1,
	},
	{
		key = "bulwark_footsteps", setting_id = "bulwark_footsteps",
		hook = {
			kind = "sound_event",
			event = "wwise/events/minions/play_minion_footsteps_chaos_ogryn",
			events = { "wwise/events/minions/play_minion_footsteps_chaos_ogryn_stomp" },
			breeds = { "chaos_ogryn_bulwark" },
		},
		audio = {
			kind = "surface",
			base = "mods/Signal Repeater/audio/cues/ogryn_footsteps",
			surfaces = "chaos_ogryn",
			gaits = { { "run", 3.75 }, { "walk", 1 }, { "scuff", 0 } },
		},
		range = 60,
		lpf = { { 0, 0 }, { 60, 45 } },
		mode = "play_once",
		overlap = true,
		gain = 0.87,
		min_interval = 0.05,
		max_duration = 1.5,
	},
	{
		key = "reaper_footsteps", setting_id = "reaper_footsteps",
		hook = {
			kind = "sound_event",
			event = "wwise/events/minions/play_minion_footsteps_chaos_ogryn",
			events = { "wwise/events/minions/play_minion_footsteps_chaos_ogryn_stomp" },
			breeds = { "chaos_ogryn_gunner" },
		},
		audio = {
			kind = "surface",
			base = "mods/Signal Repeater/audio/cues/ogryn_footsteps",
			surfaces = "chaos_ogryn",
			gaits = { { "run", 4.05 }, { "walk", 1 }, { "scuff", 0 } },
		},
		range = 60,
		lpf = { { 0, 0 }, { 60, 45 } },
		mode = "play_once",
		overlap = true,
		gain = 0.87,
		min_interval = 0.05,
		max_duration = 1.5,
	},
	{
		key = "crusher_footsteps", setting_id = "crusher_footsteps",
		hook = {
			kind = "sound_event",
			event = "wwise/events/minions/play_minion_footsteps_chaos_ogryn",
			events = { "wwise/events/minions/play_minion_footsteps_chaos_ogryn_stomp" },
			breeds = { "chaos_ogryn_executor" },
		},
		audio = {
			kind = "surface",
			base = "mods/Signal Repeater/audio/cues/ogryn_footsteps",
			surfaces = "chaos_ogryn",
			gaits = { { "run", 3.6 }, { "walk", 1 }, { "scuff", 0 } },
		},
		range = 60,
		lpf = { { 0, 0 }, { 60, 45 } },
		mode = "play_once",
		overlap = true,
		gain = 0.87,
		min_interval = 0.05,
		max_duration = 1.5,
	},
	{
		key = "trapper_laugh", setting_id = "trapper_laugh",
		hook = { kind = "sound_event", event = "wwise/events/minions/play_traitor_guard_netgunner_laugh_vce" },
		audio = { kind = "glob", pattern = "mods/Signal Repeater/audio/cues/trapper_laugh/*.ogg" },
		range = 100,
		lpf = { { 0, 0 }, { 100, 45 } },
		mode = "play_once",
		overlap = true,
		max_duration = 2.5,
	},
	{
		key = "poxburster_beep", setting_id = "poxburster_beep",
		hook = {
			kind = "breed_spawn",
			breed = "chaos_poxwalker_bomber",
		},
		audio = { kind = "glob", pattern = "mods/Signal Repeater/audio/cues/poxburster_beep/*.ogg" },
		range = 160,
		lpf = { { 0, 0 }, { 160, 30 } },
		mode = "ramped_tick",
		suppress_events = { "wwise/events/minions/play_enemy_combat_poxwalker_bomber_beep_loop" },
		ramp = {
			curve = {
				points = { { 0, 0.03 }, { 50, 1.5 } },
				min_interval = 0.12,
			},
			constant = { distance = 3.0, path = "mods/Signal Repeater/audio/cues/poxburster_constant.ogg" },
		},
	},
	{
		key = "daemonhost_aggro", setting_id = "daemonhost_aggro",
		hook = {
			kind = "sound_event",
			pattern = "^wwise/events/minions/play_enemy_daemonhost_alert_scream",
		},
		audio = { kind = "glob", pattern = "mods/Signal Repeater/audio/cues/daemonhost_aggro/*.ogg" },
		range = 120,
		lpf = { { 0, 0 }, { 120, 50 } },
		mode = "play_once",
		overlap = true,
		min_distance = 60,
		gain = 1.5,
		max_duration = 6,
	},
}
