return {
	mod_name = { en = "Signal Repeater" },
	mod_description = { en = "Re-plays important special and elite enemy cues through SimpleAudio so they are always audible." },

	cue_enabled_tooltip = { en = "Replay this cue through SimpleAudio, so it stays audible when the game's mixer ducks or muffles it." },
	cue_suppress_tooltip = { en = "Also silence the game's own version of this cue, so you hear the replay instead of both at once." },

	grp_options = { en = "Options" },
	enabled = { en = "Enabled" },
	volume = { en = "Volume" },
	volume_description = { en = "100 is slightly louder than the game's own version of the cue, so the replay stands out." },
	audible_range = { en = "Audible range" },
	audible_range_description = { en = "Scales every cue's range, as a percentage of the range the game itself uses for that cue. 100 is the same range as the game." },
	repeat_all = { en = "Repeat every cue" },
	repeat_all_description = { en = "Ticks or unticks the repeat checkbox on every cue below." },
	mute_all = { en = "Silence every original" },
	mute_all_description = { en = "Ticks or unticks the silence checkbox on every cue below." },
	sound_test = { en = "Sound test" },
	sound_test_description = { en = "Loops a hound bark circling you, so you can set the volume." },
	isolate_cues = { en = "Independent volume" },
	isolate_cues_description = { en = "Replayed cues ignore the game's SFX, Music and Dialogue sliders, so only the Volume above applies to them. The Master slider still applies." },
	debug = { en = "Debug" },
	debug_description = { en = "Prints each cue to chat as it fires." },
	sr_test = { en = "Toggle the Signal Repeater sound test" },

	grp_trapper = { en = "Trapper" },
	grp_trapper_description = { en = "Disabler. Nets you from range and drags you away." },
	trapper_windup_enabled = { en = "Net-gun wind-up" },
	trapper_windup_suppress = { en = "    ... and silence the original" },
	trapper_interrupted_enabled = { en = "Aim broken off" },
	trapper_interrupted_suppress = { en = "    ... and silence the original" },
	trapper_reload_enabled = { en = "Reload" },
	trapper_reload_enabled_description = { en = "It missed, and is reloading to try again." },
	trapper_reload_suppress = { en = "    ... and silence the original" },
	trapper_proximity_enabled = { en = "Stalking you" },
	trapper_proximity_suppress = { en = "    ... and silence the original" },
	trapper_footsteps_enabled = { en = "Footsteps" },
	trapper_footsteps_suppress = { en = "    ... and silence the original" },
	trapper_laugh_enabled = { en = "Laugh" },
	trapper_laugh_suppress = { en = "    ... and silence the original" },

	grp_hound = { en = "Chaos Hound" },
	grp_hound_description = { en = "Disabler. Pounces and pins you to the ground." },
	hound_leap_enabled = { en = "POUNCE" },
	hound_leap_suppress = { en = "    ... and silence the original" },
	hound_approach_enabled = { en = "Bark" },
	hound_approach_suppress = { en = "    ... and silence the original" },
	hound_growl_enabled = { en = "Growl" },
	hound_growl_suppress = { en = "    ... and silence the original" },
	hound_footsteps_enabled = { en = "Footsteps" },
	hound_footsteps_suppress = { en = "    ... and silence the original" },

	grp_mutant = { en = "Mutant" },
	grp_mutant_description = { en = "Disabler. Charges you down and carries you off." },
	mutant_charge_enabled = { en = "Charge growl" },
	mutant_charge_suppress = { en = "    ... and silence the original" },
	mutant_breath_enabled = { en = "Charging breath" },
	mutant_breath_suppress = { en = "    ... and silence the original" },
	mutant_rattle_enabled = { en = "Charging rattle" },
	mutant_rattle_suppress = { en = "    ... and silence the original" },
	mutant_footsteps_enabled = { en = "Footsteps" },
	mutant_footsteps_suppress = { en = "    ... and silence the original" },

	grp_poxburster = { en = "Poxburster" },
	poxburster_beep_enabled = { en = "Ticking" },
	poxburster_beep_enabled_description = { en = "The tick quickens as it closes on its target." },
	poxburster_beep_suppress = { en = "    ... and silence the original" },
	poxburster_footsteps_enabled = { en = "Footsteps" },
	poxburster_footsteps_suppress = { en = "    ... and silence the original" },

	grp_flamer = { en = "Flamer" },
	flamer_tank_enabled = { en = "Fuel tank" },
	flamer_tank_enabled_description = { en = "The idle rumble of the fuel tank. It means a flamer is near." },
	flamer_tank_suppress = { en = "    ... and silence the original" },
	flamer_aim_enabled = { en = "Taking aim" },
	flamer_aim_suppress = { en = "    ... and silence the original" },
	flamer_ignite_enabled = { en = "Proximity warning" },
	flamer_ignite_suppress = { en = "    ... and silence the original" },
	flamer_flame_dreg_enabled = { en = "Flame stream (Dreg)" },
	flamer_flame_dreg_suppress = { en = "    ... and silence the original" },
	flamer_flame_scab_enabled = { en = "Flame stream (Scab)" },
	flamer_flame_scab_suppress = { en = "    ... and silence the original" },
	dreg_flamer_footsteps_enabled = { en = "Footsteps (Dreg)" },
	dreg_flamer_footsteps_suppress = { en = "    ... and silence the original" },
	scab_flamer_footsteps_enabled = { en = "Footsteps (Scab)" },
	scab_flamer_footsteps_suppress = { en = "    ... and silence the original" },

	grp_bomber = { en = "Bomber" },
	bomber_footsteps_enabled = { en = "Footsteps" },
	bomber_footsteps_suppress = { en = "    ... and silence the original" },

	grp_sniper = { en = "Sniper" },
	sniper_aim_enabled = { en = "Aim beam" },
	sniper_aim_suppress = { en = "    ... and silence the original" },
	sniper_footsteps_enabled = { en = "Footsteps" },
	sniper_footsteps_suppress = { en = "    ... and silence the original" },

	grp_plasma = { en = "Plasma Gunner" },
	plasma_charge_enabled = { en = "Charge-up" },
	plasma_charge_suppress = { en = "    ... and silence the original" },

	grp_daemonhost = { en = "Daemonhost" },
	daemonhost_aggro_enabled = { en = "Alert scream" },
	daemonhost_aggro_suppress = { en = "    ... and silence the original" },

	grp_reaper = { en = "Reaper" },
	reaper_vo_alerted_enabled = { en = "Callout: spots you" },
	reaper_vo_alerted_suppress = { en = "    ... and silence the original" },
	reaper_vo_shooting_enabled = { en = "Callout: opening fire" },
	reaper_vo_shooting_suppress = { en = "    ... and silence the original" },
	reaper_ready_enabled = { en = "Readying gun" },
	reaper_ready_suppress = { en = "    ... and silence the original" },
	reaper_fire_enabled = { en = "Heavy stubber" },
	reaper_fire_suppress = { en = "    ... and silence the original" },
	reaper_melee_enabled = { en = "Melee swing" },
	reaper_melee_suppress = { en = "    ... and silence the original" },
	reaper_footsteps_enabled = { en = "Footsteps" },
	reaper_footsteps_suppress = { en = "    ... and silence the original" },

	grp_crusher = { en = "Crusher" },
	crusher_vo_alerted_enabled = { en = "Callout: spots you" },
	crusher_vo_alerted_suppress = { en = "    ... and silence the original" },
	crusher_vo_assault_enabled = { en = "Callout: charging you" },
	crusher_vo_assault_suppress = { en = "    ... and silence the original" },
	crusher_special_enabled = { en = "Overhead smash" },
	crusher_special_suppress = { en = "    ... and silence the original" },
	crusher_melee_enabled = { en = "Melee swing" },
	crusher_melee_suppress = { en = "    ... and silence the original" },
	crusher_swing_enabled = { en = "Hammer swing" },
	crusher_swing_suppress = { en = "    ... and silence the original" },
	crusher_footsteps_enabled = { en = "Footsteps" },
	crusher_footsteps_suppress = { en = "    ... and silence the original" },

	grp_bulwark = { en = "Bulwark" },
	bulwark_ready_enabled = { en = "Readying up" },
	bulwark_ready_suppress = { en = "    ... and silence the original" },
	bulwark_special_enabled = { en = "Overhead smash" },
	bulwark_special_suppress = { en = "    ... and silence the original" },
	bulwark_swing_enabled = { en = "Shield swing" },
	bulwark_swing_suppress = { en = "    ... and silence the original" },
	bulwark_melee_enabled = { en = "Melee swing" },
	bulwark_melee_suppress = { en = "    ... and silence the original" },
	bulwark_footsteps_enabled = { en = "Footsteps" },
	bulwark_footsteps_suppress = { en = "    ... and silence the original" },

	grp_mauler = { en = "Mauler" },
	mauler_special_enabled = { en = "Overhead smash" },
	mauler_special_suppress = { en = "    ... and silence the original" },
	mauler_swing_enabled = { en = "Chainaxe swing" },
	mauler_swing_suppress = { en = "    ... and silence the original" },
	mauler_melee_enabled = { en = "Melee swing" },
	mauler_melee_suppress = { en = "    ... and silence the original" },
	mauler_footsteps_enabled = { en = "Footsteps" },
	mauler_footsteps_suppress = { en = "    ... and silence the original" },

}
