return {
	mod_name = { en = "Signal Repeater" },
	mod_description = { en = "Re-plays important special and elite enemy cues through SimpleAudio so they are always audible." },

	grp_options = { en = "Options" },
	enabled = { en = "Enabled" },
	repeat_all = { en = "Repeat every cue below (ticks/unticks all)" },
	mute_all = { en = "Silence the game's own cue for all of them (ticks/unticks all)" },
	volume = { en = "Volume of our cues (100 = as loud as the game's own)" },
	audible_range = { en = "Audible range, as a percentage of the game's own range per cue (100 = the same)" },
	sound_test = { en = "Sound test: loop a hound bark circling you, to set volume" },
	isolate_cues = { en = "Independent volume: ignore the game's audio sliders entirely (only the Volume above applies)" },
	debug = { en = "Debug: print each cue to chat as it fires" },
	sr_test = { en = "Toggle the Signal Repeater sound test" },

	grp_trapper = { en = "Trapper  (disabler)" },
	trapper_windup_enabled = { en = "Net-gun wind-up" },
	trapper_windup_suppress = { en = "    ... and silence the game's own" },
	trapper_interrupted_enabled = { en = "Aim broken off" },
	trapper_interrupted_suppress = { en = "    ... and silence the game's own" },
	trapper_reload_enabled = { en = "Reload (it will try again)" },
	trapper_reload_suppress = { en = "    ... and silence the game's own" },
	trapper_proximity_enabled = { en = "Stalking you" },
	trapper_proximity_suppress = { en = "    ... and silence the game's own" },
	trapper_footsteps_enabled = { en = "Footsteps" },
	trapper_footsteps_suppress = { en = "    ... and silence the game's own" },
	trapper_laugh_enabled = { en = "Laugh" },
	trapper_laugh_suppress = { en = "    ... and silence the game's own" },

	grp_hound = { en = "Chaos Hound  (disabler)" },
	hound_leap_enabled = { en = "POUNCE" },
	hound_leap_suppress = { en = "    ... and silence the game's own" },
	hound_approach_enabled = { en = "Bark" },
	hound_approach_suppress = { en = "    ... and silence the game's own" },
	hound_growl_enabled = { en = "Growl" },
	hound_growl_suppress = { en = "    ... and silence the game's own" },
	hound_footsteps_enabled = { en = "Footsteps" },
	hound_footsteps_suppress = { en = "    ... and silence the game's own" },

	grp_mutant = { en = "Mutant  (disabler)" },
	mutant_charge_enabled = { en = "Charge growl" },
	mutant_charge_suppress = { en = "    ... and silence the game's own" },
	mutant_breath_enabled = { en = "Charging breath" },
	mutant_breath_suppress = { en = "    ... and silence the game's own" },
	mutant_rattle_enabled = { en = "Charging rattle" },
	mutant_rattle_suppress = { en = "    ... and silence the game's own" },
	mutant_footsteps_enabled = { en = "Footsteps" },
	mutant_footsteps_suppress = { en = "    ... and silence the game's own" },

	grp_poxburster = { en = "Poxburster" },
	poxburster_beep_enabled = { en = "Ticking" },
	poxburster_beep_suppress = { en = "    ... and silence the game's own" },
	poxburster_footsteps_enabled = { en = "Footsteps" },
	poxburster_footsteps_suppress = { en = "    ... and silence the game's own" },

	grp_flamer = { en = "Flamer" },
	flamer_tank_enabled = { en = "Fuel tank (it is near)" },
	flamer_tank_suppress = { en = "    ... and silence the game's own" },
	flamer_aim_enabled = { en = "Taking aim" },
	flamer_aim_suppress = { en = "    ... and silence the game's own" },
	flamer_ignite_enabled = { en = "Proximity warning" },
	flamer_ignite_suppress = { en = "    ... and silence the game's own" },
	flamer_flame_dreg_enabled = { en = "Flame stream (Dreg)" },
	flamer_flame_dreg_suppress = { en = "    ... and silence the game's own" },
	flamer_flame_scab_enabled = { en = "Flame stream (Scab)" },
	flamer_flame_scab_suppress = { en = "    ... and silence the game's own" },
	dreg_flamer_footsteps_enabled = { en = "Footsteps (Dreg)" },
	dreg_flamer_footsteps_suppress = { en = "    ... and silence the game's own" },
	scab_flamer_footsteps_enabled = { en = "Footsteps (Scab)" },
	scab_flamer_footsteps_suppress = { en = "    ... and silence the game's own" },

	grp_bomber = { en = "Bomber" },
	bomber_footsteps_enabled = { en = "Footsteps" },
	bomber_footsteps_suppress = { en = "    ... and silence the game's own" },

	grp_sniper = { en = "Sniper" },
	sniper_aim_enabled = { en = "Aim beam" },
	sniper_aim_suppress = { en = "    ... and silence the game's own" },
	sniper_footsteps_enabled = { en = "Footsteps" },
	sniper_footsteps_suppress = { en = "    ... and silence the game's own" },

	grp_plasma = { en = "Plasma Gunner" },
	plasma_charge_enabled = { en = "Charge-up" },
	plasma_charge_suppress = { en = "    ... and silence the game's own" },

	grp_daemonhost = { en = "Daemonhost" },
	daemonhost_aggro_enabled = { en = "Alert scream" },
	daemonhost_aggro_suppress = { en = "    ... and silence the game's own" },

	grp_reaper = { en = "Reaper" },
	reaper_vo_alerted_enabled = { en = "Callout: spots you" },
	reaper_vo_alerted_suppress = { en = "    ... and silence the game's own" },
	reaper_vo_shooting_enabled = { en = "Callout: opening fire" },
	reaper_vo_shooting_suppress = { en = "    ... and silence the game's own" },
	reaper_ready_enabled = { en = "Readying gun" },
	reaper_ready_suppress = { en = "    ... and silence the game's own" },
	reaper_fire_enabled = { en = "Heavy stubber" },
	reaper_fire_suppress = { en = "    ... and silence the game's own" },
	reaper_melee_enabled = { en = "Melee swing" },
	reaper_melee_suppress = { en = "    ... and silence the game's own" },
	reaper_footsteps_enabled = { en = "Footsteps" },
	reaper_footsteps_suppress = { en = "    ... and silence the game's own" },

	grp_crusher = { en = "Crusher" },
	crusher_vo_alerted_enabled = { en = "Callout: spots you" },
	crusher_vo_alerted_suppress = { en = "    ... and silence the game's own" },
	crusher_vo_assault_enabled = { en = "Callout: charging you" },
	crusher_vo_assault_suppress = { en = "    ... and silence the game's own" },
	crusher_special_enabled = { en = "Overhead smash" },
	crusher_special_suppress = { en = "    ... and silence the game's own" },
	crusher_melee_enabled = { en = "Melee swing" },
	crusher_melee_suppress = { en = "    ... and silence the game's own" },
	crusher_swing_enabled = { en = "Hammer swing" },
	crusher_swing_suppress = { en = "    ... and silence the game's own" },
	crusher_footsteps_enabled = { en = "Footsteps" },
	crusher_footsteps_suppress = { en = "    ... and silence the game's own" },

	grp_bulwark = { en = "Bulwark" },
	bulwark_ready_enabled = { en = "Readying up" },
	bulwark_ready_suppress = { en = "    ... and silence the game's own" },
	bulwark_special_enabled = { en = "Overhead smash" },
	bulwark_special_suppress = { en = "    ... and silence the game's own" },
	bulwark_swing_enabled = { en = "Shield swing" },
	bulwark_swing_suppress = { en = "    ... and silence the game's own" },
	bulwark_melee_enabled = { en = "Melee swing" },
	bulwark_melee_suppress = { en = "    ... and silence the game's own" },
	bulwark_footsteps_enabled = { en = "Footsteps" },
	bulwark_footsteps_suppress = { en = "    ... and silence the game's own" },

	grp_mauler = { en = "Mauler" },
	mauler_special_enabled = { en = "Overhead smash" },
	mauler_special_suppress = { en = "    ... and silence the game's own" },
	mauler_swing_enabled = { en = "Chainaxe swing" },
	mauler_swing_suppress = { en = "    ... and silence the game's own" },
	mauler_melee_enabled = { en = "Melee swing" },
	mauler_melee_suppress = { en = "    ... and silence the game's own" },
	mauler_footsteps_enabled = { en = "Footsteps" },
	mauler_footsteps_suppress = { en = "    ... and silence the game's own" },

}
